### ISSUE TITLE
Remove grunt from all this

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-template#1]

**Comment by groovecoder** [comment]
I'm taking a try at this and #2 right now. Will push my branch up here.

**Comment by groovecoder** [comment]
This will require a non-grunt implementation of/in/with `istanbul-jpm` to keep its test coverage features.

**Comment by gregglind** [comment]
DONE, killed with fire, pulling over all the new template stuff, which has no grunt.
