### ISSUE TITLE
What Template SHOULD be able to do

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-template#10]
Running list of the GUARANTEES you should get from using the template.
- [x] All files lint
- [x] testing
- [x] dependency checks for all modules  **Doesn't catch missing, but code coverage does**
- [x] consistent package.json (fixpack)
- [x] continuous integration  <- **TRAVIS ONLY**
- [x] shrinkwrap
- [x] code coverage
- [x] addon-linter
- [x] nsp

**Comment by gregglind** [comment]
@pdehaan thoughts?  Other contract? Add them if so!

**Comment by gregglind** [comment]
- depcheck still stinks.  
- ci is unclear
- need to finish up tests for 100% coverage of the basic addon

**Comment by pdehaan** [comment]
Yeah, **depcheck** and similar are still awkward when we do things like `require('chrome')` and `require('sdk')` for add-ons stuff. https://github.com/mcasimir/depcheck-ci seems a bit better, but still uses depcheck under the hood.

Only other ones I could think of is integrating [**addons-linter**](https://www.npmjs.com/package/addons-linter) and [**nsp**](https://www.npmjs.com/package/nsp).

**Comment by gregglind** [comment]
I claim all of these now work, for some values of work.

**Comment by gregglind** [comment]
Is it worth doing Circle CI and / or doing something different to catch the 'missing' keys?  

Filed at: https://github.com/mcasimir/depcheck-ci/issues/2

**Comment by gregglind** [comment]
TODO: update this bug for hte new template.

**Comment by motin** [comment]
These (except possibly dependency checking) are all covered in the new web extension based template.

**Comment by motin** [comment]
Closing since #73 is merged
