### ISSUE TITLE
Update or deprecate this repository

### ISSUE THREAD

**Issue by motin** [mozilla/shield-studies-addon-template#16]
This repository's organization and name suggests this is the official template for new Shield add-ons. 

Please update or remove this repository, or at least clarify that it is not maintained, refer to more up-to-date-template.

Candidate template to use instead:

[https://github.com/gregglind/template-shield-study]() - According to Shield engineers, the most up to date shield study template as of 4th October 2017, albeit with incomplete documentation. UPDATE: The documentation has been vastly updated and improved

**Comment by gregglind** [comment]
DOING IT RIGHT NOW, and KILLING - http://github.com/gregglind/template-shield-study
