### ISSUE TITLE
Template is too opinionated!

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-template#2]
So, where can we rip things out?

**Comment by groovecoder** [comment]
My suggestions, which I plan to try in a branch:

* [ ] Remove grunt (#1)
* [ ] Remove chai
  * Devs can use their own test runner, and it makes the template fail depcheck-ci
* [ ] Remove istanbul
  * Devs may prefer their own coverage tool
* [ ] Remove the 100% code coverage threshold
  * [Code coverage is useful, but coverage targets are not](http://blog.ploeh.dk/2015/11/16/code-coverage-is-a-useless-target-measure/)
  * Add-on code necessarily uses a number of underlying APIs that may be hard to mock for testing
* [ ] Remove `eslint`
  * Devs may prefer their own standard/style

**Comment by gregglind** [comment]
1.  I have discovered no other code-coverage tool for firefox addons other than `istanbul-jpm`.  I am open to be corrected.  Even making *that one* work was a huge huge challenge.  It's why `grunt` in in the chain at all.  

2.  The 100% target is there because I want to *explicitly see all skipped (non-covered) code*.  Istanbul does this by making you comment near anything needing skipping.  I do agree that Fx addons are super hard to mock.

3.  Eslint.  if devs want to change their style rules, they may edit the existing eslintrc.

**Comment by groovecoder** [comment]
Those make sense. The only thing/opinion we can actually remove then is `chai`. I'll just do that.

**Comment by gregglind** [comment]
Closed, started from scratch.
