### ISSUE TITLE
starting new projects

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-template#20]
- git archive, would be ideal but github doesn't support it.
  https://www.gilesorr.com/blog/git-archive-github.html
- https://stackoverflow.com/questions/3946538/git-clone-just-the-files-please 

$ curl -L https://github.com/mozilla/shield-studies-addon-template/tarball/master > ssat.head.zip

Annoyingly, it puts it all in a directory with the name based on the commit.

**Comment by gregglind** [comment]
```
10791 glind ~/gits $ tar -tf t.zip
mozilla-shield-studies-addon-template-6f03898/
mozilla-shield-studies-addon-template-6f03898/.circleci/
mozilla-shield-studies-addon-template-6f03898/.circleci/config.yml
mozilla-shield-studies-addon-template-6f03898/.eslintignore
mozilla-shield-studies-addon-template-6f03898/.eslintrc.js
mozilla-shield-studies-addon-template-6f03898/.gitignore
```


But at least no `.git/` directory.

**Comment by gregglind** [comment]
This is better:

```
10798 glind ~/gits $ curl -sL https://github.com/mozilla/shield-studies-addon-template/archive/master.tar.gz | tar -t
shield-studies-addon-template-master/
shield-studies-addon-template-master/.circleci/
shield-studies-addon-template-master/.circleci/config.yml
shield-studies-addon-template-master/.eslintignore
shield-studies-addon-template-master/.eslintrc.js
```

**Comment by gregglind** [comment]
Suggested flow
```
## mkdir directory, cd into it, barf out all template files there.

mkdir yourproject &&  mkdir blah && cd !$   
curl -sL https://github.com/mozilla/shield-studies-addon-template/archive/master.tar.gz | tar -x --strip-components 1
```

**Comment by motin** [comment]
Closing with https://github.com/mozilla/shield-studies-addon-template/pull/98 since there is a documented way of starting new projects both from scratch and from an existing repo is documented in the new docs/TEMPLATE.md docs.
It may not be ideal, but improvements to the documented ways can be proposed as new issues.
