### ISSUE TITLE
ENH: npm run kitchensink

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-template#25]
@motin:  what do you propose would be in this, do demonstrate EVERYTHING IT DOES

**Comment by motin** [comment]
Exactly, the `npm run kitchensink` command (or `npm run demo`) would showcase all possible re-usable webdriver-related things, like clicking different parts of a website, searching in the searchbar, taking screenshots, showing telemetry pings, opening windows/tabs, opening the web extension popdown/doorhanger, showing a notification bar etc, anything useful for shield experimentation that has been used in previous studies and potentially useful for future studies.

**Comment by motin** [comment]
Closing this since the template serves the purpose of showing existing integration, testing etc
