### ISSUE TITLE
What is a good README for a shield study?

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-template#26]

**Comment by gregglind** [comment]
This might be a good start:

https://github.com/Standard8/example-webextension/

**Comment by motin** [comment]
(Moving your comments from the previous issue here:)

Claim:

- [ ] description of goal
- [ ] list of files
- [ ] list of variations
- [ ] links to TELEMETRY and TESTPLAN
- [ ] bug number?  Maybe this should be in the description as well?
- [ ] build / run instructions?

Probably not:

- [ ] how to contribute?  


Other thoughts welcome... we are trying to pave this path.
- claim should name / id of the study have both pioneer and shield in them?  @esper-pioneer-shield-mozilla?   This makes regex searching by id have a hope of succeeding :)

**Comment by motin** [comment]
Closing this since a good enough readme (as proved by multiple study deployments) is sported in the [template](https://github.com/mozilla/shield-studies-addon-template)
