### ISSUE TITLE
enable coverage testing, for at least some parts of the code base.

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-template#27]
starting from:  https://github.com/Standard8/example-webextension/blob/ca04169360330856696c83d6b4e3455e44835552/karma.conf.js

**Comment by gregglind** [comment]
This requires karma, maybe.  we use mocha for testing.  I think I am not smart enough to make this work.

**Comment by gregglind** [comment]
Ideas:

- start from:  https://github.com/freaktechnik/istanbul-jpm/blob/master/index.js
- covere the f
- have a jsm in the build addon that has the coverage object and is injected everywhere as the preamble
- make sure that when that is unloaded it dumps.

**Comment by motin** [comment]
This is fixed by https://github.com/mozilla/shield-studies-addon-template/pull/73
