### ISSUE TITLE
Rename generated XPI file instead of creating a sym-link?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/shield-studies-addon-template#42]
Per https://github.com/gregglind/addon-wr/issues/17

> Instead of generating a symbolic link to the generated XPI, why not just do a `mv "${XPI_NAME}" addon.xpi`? (Or even `mv *.xpi addon.xpi`, if the /dist/ directory only has one XPI file)
>
> https://github.com/gregglind/addon-wr/blob/526535ea04ce79f59a79381ab71b8c9be61b9af8/bin/xpi.sh#L39-L49

**Comment by motin** [comment]
Keeping the filename intact (with guid and version) is important to be able to be sure that we submit the correct xpi for signing and deployment. 
The dist directory will over the lifetime of developing addons contain builds of all the different versions built by the developer.

**Comment by motin** [comment]
Related: https://github.com/mozilla/shield-studies-addon-template/issues/75

**Comment by motin** [comment]
Closing as wontfix
