### ISSUE TITLE
`linked-addon.xpi` fails to load in Firefox Developer Edition (outdated README?)

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/shield-studies-addon-template#43]
The [readme](https://github.com/mozilla/shield-studies-addon-template/blame/master/README.md#L180) file reports, in the "Load The WebExtension in Firefox" section, the following step:

> Find and select the `linked-addon.xpi` file you just built.

However, loading that XPI fails on Firefox Developer Edition 59.0b2 (64bit, build id 20180117222144), with the error:

> `linked-addon.xpi` unable to access the file.

Is the README outdated? I can correctly load the other generated file (i.e. `button-icon-preference@shield-study.mozilla.com-1.2.0.xpi`).

**Comment by motin** [comment]
This has been addressed in #73
