### ISSUE TITLE
`feature.shutdown()` must happen before unloading `Feature.jsm`

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/shield-studies-addon-template#44]
When shutting down the [`feature.shutdown`](https://github.com/mozilla/shield-studies-addon-template/blob/68915f9a8d7077b7bcfe1e7932b1b45ecf56b39b/addon/bootstrap.js#L133) method is called *after* the `Feature.jsm` module is unloaded.

This can potentially make the shutdown procedure fail, as dependent modules might have already been unloaded.

**Comment by gregglind** [comment]
(Shutdown is the worst.   Addon unload and modules unload race in unpredictable ways.)
