### ISSUE TITLE
proposed: all study addons must have id's ending with @shield.mozilla.org

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-template#46]
See #45 

Proposed:  For easy regex identification by analysts, dashboard makers, and other consumers, **require** all study addons to have addon id's ending with `@shield.mozilla.org`.  

Before implementation, attempt to gather feedback about the impact.

See:
- https://github.com/meandavejustice/min-vid/issues/1257

Possible side effects:
- pref names being messed up when a study moves from TP => shield.
- co-existence of TP and SHIELD studies.

**Comment by motin** [comment]
A PR related to this was recently merged into master: https://github.com/mozilla/shield-studies-addon-template/pull/45

**Comment by motin** [comment]
Moved to https://github.com/mozilla/shield-studies-addon-utils/issues/209
