### ISSUE TITLE
Leave users alone if they are in Private Browsing mode

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/shield-studies-addon-template#51]
We should not collect any data when a user is in Private Browsing mode. More broadly, we should simply leave them alone (no prompts, no UI, etc.).

This is not a clear requirement in the README or anywhere else AFAIK, so let's be sure to make it explicit both in the template's README and in its behavior and comments.

**Comment by biancadanforth** [comment]
In addition to checking for Private Browsing windows, it is also possible for users to set a preference (`browser.privatebrowsing.autostart`) such that all windows are Private Browsing windows by default, including the first window on startup. I just learned about this through QA in my Tracking Protection Messaging study.

The [patch](https://github.com/biancadanforth/tracking-protection-shield-study/commit/93cd422597ac90a52882448a768d72ed43eedaa3) from the issue in that repo should be added here. I.e. we should update the `isEligible` method in `Config.jsm` in the template to check for this pref.

**Comment by motin** [comment]
Let's use https://github.com/mozilla/shield-studies-addon-utils/issues/252 to discuss what the appropriate behavior is. 
Then we can backport privacy-related code from https://github.com/motin/taar-experiment-v3-shield-study which explicitly is put in place to not bother users when in private browsing mode.

**Comment by motin** [comment]
Closing since privacyContext WEE has been including the template including usage example since https://github.com/mozilla/shield-studies-addon-template/pull/95
