### ISSUE TITLE
Support Web Extension Experiments workflows in this template

### ISSUE THREAD

**Issue by motin** [mozilla/shield-studies-addon-template#53]
The template has been sporting a hybrid legacy add-on / web extension workflow for quite a while now, but it still requires messaging between the web extension and legacy add-on code to workaround the limitations of the web extension apis. A first step is to remove the need for this messaging and instead craft web extension apis to remove need for legacy code for common study operations. 

This should take is one step further away from legacy add-ons and towards a full web-extension-based workflow as described in https://github.com/mozilla/shield-studies-addon-utils/issues/45

**Comment by motin** [comment]
Current efforts: 
- @biancadanforth is setting up a prototype at https://github.com/biancadanforth/shield-study-webextension-experiment-template that will give us a good idea of what works and what does not work with web extension experiments
- We both are planning to experiment with this in upcoming shield study add-ons

**Comment by motin** [comment]
Depends on: https://github.com/mozilla/shield-studies-addon-utils/issues/60

**Comment by motin** [comment]
Related: [Bug 1280234 - Allow Telemetry to be sent to Mozilla from a WebExtension]
(https://bugzilla.mozilla.org/show_bug.cgi?id=1280234#c31)

**Comment by motin** [comment]
Related (available in 59): [Bug 1323845 - Allow bundled experiments, and support for content-side APIs](https://bugzilla.mozilla.org/show_bug.cgi?id=1323845)

**Comment by biancadanforth** [comment]
Just as an update: I have not yet had the opportunity to work on a study that takes the form of a WEE, which is how I was going to make the template. Please see the [README](../blob/master/README.md) for examples in the meantime until the official template is built.

**Comment by motin** [comment]
> which is how I was going to make the template.

The template is already a WEE (the develop branch). See https://github.com/mozilla/shield-studies-addon-template/pull/64 for the latest progress.

Maybe merge that one and then enhance the template further based on the develop branch?

**Comment by motin** [comment]
Update: The develop-branch of this template is now a study add-on with a bundled Web Extension Experiment, using [the latest release candidate of Shield Utils v5](https://github.com/mozilla/shield-studies-addon-utils/pull/180/)
