### ISSUE TITLE
Delete/Close all old issues/PRs/branches

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/shield-studies-addon-template#59]
If there's anything valuable in these old artifacts, let's create a new issue that distills all of that in one place. Ideally we have only recently made PRs/issues that are still relevant and clearly defined at the end.

**Comment by motin** [comment]
Done. I went through all open issues, PRs and branches. Closed old issues and notes which ones will be fixed with the web extension based workflows. Removed the stale coverage-testing branch (did not even contain any wip code about coverage testing)
