### ISSUE TITLE
Take care of breaking changes in Firefox 61

### ISSUE THREAD

**Issue by motin** [mozilla/shield-studies-addon-template#65]
From: https://mail.mozilla.org/pipermail/firefox-dev/2018-April/006379.html

> Over at https://bugzilla.mozilla.org/show_bug.cgi?id=1034036 <https://bugzilla.mozilla.org/show_bug.cgi?id=1034036> I’m about to land the following changes:
> RecentWindow.jsm and UpdateTopLevelContentWindowIDHelper.jsm have been merged into one module called ‘BrowserWindowTracker.jsm’.
> Meaning the first two mentioned modules will cease to exist.
> The `getMostRecentBrowserWindow` method that was part of ye olde RecentWindow.jsm has been renamed to `getTopWindow`.
> Browser order is now tracked entirely in the JS realm, which means we’ll be able to stop crossing the XPCOM boundary with nsIWindowMediator soon.
> Meaning we’ll finally have proper window order information on Linux,
> `getTopWindow` will switch to use this local info in a follow-up bug, where the Captive Portal tests will be fixed (the only blocker).

@gregglind @biancadanforth I suggest that we fix this without maintaining backwards compatibility and set a minimum version of 61 for the template.

**Comment by gregglind** [comment]
+1000.  Window tracking in general can stop soon, for most projects.
