### ISSUE TITLE
DOCS: Provide guidelines on how all Shield add-on studies should behave in general cases

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/shield-studies-addon-template#68]
From Krupa:
> would it be possible to have general guidelines on how all SHIELD add-on studies behave when it comes to uninstall/remove actions by users?
> i see a long email thread about what the expected behavior should be for https://github.com/jonathanKingston/http-dns/issues/13

My thoughts:
The v4 Shield Utils API takes care of uninstalling the add-on if the user opts out of the study via an API method; however the study Krupa linked does not use the Shield Utils API, which explains the discrepancy. I agree that it would be:
* good to have this documented somewhere, and possibly
* require that all devs use the Shield Utils API for Shield studies.

Either way, we have been discussing whether or not to uninstall the add-on when the study ends, and those kinds of decisions and rationales should be documented somewhere. Establishing these guidelines may require some collaboration with UX, data, legal, etc.

**Comment by motin** [comment]
+1
A better place to have it would probably be in the utils repo, so that each specific study can refer to utils as is done in https://github.com/mozilla/shield-studies-addon-template/blob/master/docs/TELEMETRY.md#shield-study-pings-common-to-all-shield-studies

**Comment by motin** [comment]
Moved to https://github.com/mozilla/shield-studies-addon-utils/issues/252
