### ISSUE TITLE
Bootstrap should also shutdown the webextension component

### ISSUE THREAD

**Issue by Standard8** [mozilla/shield-studies-addon-template#69]
I was just reviewing some changes elsewhere, and it highlighted to me that the bootstrap.js in this template isn't shutting down the WebExtension component.

For example, this is what screenshots does currently:

https://searchfox.org/mozilla-central/rev/83a923ef7a3b95a516f240a6810c20664b1e0ac9/browser/extensions/screenshots/bootstrap.js#141-148,203

This could cause issues if the add-on is upgraded whilst a study is running. It could also leave the WebExtension part running if the study gets uninstalled.

I don't know how likely it is to cause issues on shutdown or not.

**Comment by gregglind** [comment]
Thank you for this.  We are trying to deprecate master (and legacy) here, and trying to move to WEE's which will have no bootstrap.js files.

See:  https://github.com/mozilla/shield-studies-addon-template/tree/develop

**Comment by motin** [comment]
Closing since #73 is merged and we thus are no longer promoting legacy bootstrapped add-ons
