### ISSUE TITLE
npm deprecate the old V4 branch?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/shield-studies-addon-template#74]
@gregglind was saying the V4 API is no longer supported, and the new path to salvation is the V5 API.
From the looks of it, we did a npm package.json version bump version from 1.3.0(?) to 2.0.0. Not sure if there is some way of using [`npm deprecate`](https://docs.npmjs.com/cli/deprecate) to say:

```sh
npm deprecate shield-studies-addon-template@"< 2.0.0" "Only shield study V5 WEE experiments are supported"
```

... but maybe that won't work due to the fact people are <kbd>git clone</kbd>ing the repo and not installing via npm.

**Comment by motin** [comment]
Yes, I think the idea is to not publish this with npm at all. Related: https://github.com/mozilla/shield-studies-addon-template/issues/21

**Comment by motin** [comment]
Closing since the npm package is marked as deprecated with instructions to clone directly from github instead. Npm should not be used to interact/consume the template at this point.
