### ISSUE TITLE
The Node Security Platform (nsp) service is shutting down 9/30

### ISSUE THREAD

**Issue by pdehaan** [mozilla/shield-studies-addon-template#77]
Looks like we should replace **nsp** with npm's new <kbd>$ nsp audit</kbd>.

https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting

> npm now automatically reviews every install request against the NSP vulnerability database and warns you if you try to use unsafe code. Additionally, beginning with npm@6, a new command, npm audit, recursively analyzes your dependency trees to identify specifically what’s insecure, recommend a replacement, or fix it automatically with npm audit fix.

Sadly, I don't think that `npm audit` is supported in npm@5 yet.

```sh
$  nvm i 8
v8.11.3 is already installed.
Now using node v8.11.3 (npm v5.6.0)

$ npm audit

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
    explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, profile, prune,
    publish, rb, rebuild, repo, restart, root, run, run-script,
    s, se, search, set, shrinkwrap, star, stars, start, stop, t,
    team, test, token, tst, un, uninstall, unpublish, unstar,
    up, update, v, version, view, whoami
```

So we may be able to "fix" this by requiring npm@6, or using `npm audit` via <kbd>npx npm@6 audit</kbd>, although that can be pretty slow since we're basically installing npm@6 at runtime (~16 second penalty), versus requiring npm@6 be installed globally (or forcing people to use node@10).

Conversely, we could just not include **nsp** or `npm audit` until support is a bit better.

**Comment by motin** [comment]
Closing since nsp has been removed in https://github.com/mozilla/shield-studies-addon-template/pull/95/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L43
