### ISSUE TITLE
find ways to remind people to install nightly / run with nightly

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-template#78]

**Comment by motin** [comment]
Counter-suggestion: Let's recommend add-on engineers to install Firefox Developer Edition and run with that as default, even skipping the necessity for 

Dev Edition can be used with unsigned extensions (just like Nightly), bit it is usually at par with Firefox Beta when it comes to stability. Most studies are designed to run on current release or +1, so testing with dev edition should be enough for most study add-on engineers. 

Nightly is many times too unstable for productive work, with random errors in CI and in testing that maybe gets resolved after a few days, or not.

The only argument I see for testing against nightly is to help out testing and reporting bugs in Nightly, or for studies that are engineering many months before they are planned to be shipped.

**Comment by motin** [comment]
Here is an example of how using Nightly interferes with development workflows - Nightly crashes on Linux in CI but passes on Dev Edition: https://github.com/mozilla/shield-studies-addon-template/pull/73#issuecomment-408768852

**Comment by motin** [comment]
Closing this since nightly is the default configured flavor that web-ext uses. If nightly is not installed, an error message reminds people to install nightly.
