### ISSUE TITLE
Preferences is not define in Firefox Nightly

### ISSUE THREAD

**Issue by vbudhram** [mozilla/shield-studies-addon-template#94]
It seems that today Firefox Nightly `67.0a1 (2019-01-29) (64-bit)` broke the template. The buttons are non-responsive and the study doesn't end after 3 clicks. Template works in older unbranded Firefox.

Browser console logs `Preferences is not define` which I don't remember seeing before.

<img width="762" alt="screen shot 2019-01-29 at 3 32 53 pm" src="https://user-images.githubusercontent.com/1295288/51938615-89e7f180-23db-11e9-98ad-63f354548641.png">

**Comment by philbooth** [comment]
Is this related to the changes in [bug 1514594](https://bugzilla.mozilla.org/show_bug.cgi?id=1514594)? The `ChromeUtils.import` statements need to change.

**Comment by motin** [comment]
It is related indeed, but closing this since the testingOverrides webextension experiment API is removed in #95 since it is now a part of shield-studies-addon-utils since version 5.1.0.
Please follow https://github.com/mozilla/shield-studies-addon-utils/issues/283 instead. Thanks
